[project]
name = "netcdf-mcp"
version = "0.1.0"
description = "MCP server for reading and understanding NetCDF files"
readme = "README.md"
authors = [
    { name = "Dogukan Teber" }
]
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]",
    "xarray",
    "netCDF4",
]

[project.scripts]
netcdf-mcp = "netcdf_mcp.server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
